development:
    adapter: postgresql
    host: localhost
    database: e-verification_development
    username: postgres
    password: sunil


production:
    adapter: postgresql
    host: localhost
    database: e-verification_production
    username: yogesh
    password: yogesh1985
